---
- name: Run aoede in docker container
  hosts: all
  become: true
  gather_facts: false

  vars:
    copy_origin_path: "../build/aoede.tar.gz"
    copy_destiny_path: "/home/ubuntu/containers/aoede.tar.gz"
    image_version: "0.7.1"
    image_name: "aoede"
    container_name: "andre-marques-bot"
    spotify_bot_autoplay: "false"

  vars_prompt:
    - name: discord_token
      private: false
      prompt: "Enter the DISCORD_APP_TOKEN"
      salt_size: 8
      unsafe: false

    - name: spotify_username
      private: false
      prompt: "Enter the SPOTIFY_USERNAME"
      salt_size: 8
      unsafe: false

    - name: spotify_password
      private: false
      prompt: "Enter the SPOTIFY_PASSWORD"
      salt_size: 8
      unsafe: false

  tasks:

  - name: Copy docker image
    ansible.builtin.copy:
      src: "{{ copy_origin_path }}"
      dest: "{{ copy_destiny_path }}"
  
  - name: Load image
    community.docker.docker_image:
      load_path: "{{ copy_destiny_path }}"
      source: load
      name: "{{ image_name }}"
      tag: "{{ image_version }}"

  - name: Run container
    async: 360
    poll: 1
    community.docker.docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      state: started
      restart_policy: always
      env:
        DISCORD_TOKEN: "{{ discord_token }}"
        SPOTIFY_USERNAME: "{{ spotify_username }}"
        SPOTIFY_PASSWORD: "{{ spotify_password }}"
        SPOTIFY_BOT_AUTOPLAY: "{{ spotify_bot_autoplay }}"
  
  - name: Clean docker old images
    async: 30
    poll: 1
    community.docker.docker_prune:
      images: true
