---
- name: Run Evobot in docker container
  hosts: all
  become: true
  gather_facts: false

  vars:
    copy_origin_path: ../build/evobot.tar.gz
    copy_destiny_path: /home/ubuntu/containers/evobot.tar.gz
    image_version: 2.8.1
    image_name: evobot
    container_name: cleiton-rasta-bot
    evobot_max_playlist_size: 100
    evobot_locale: pt_br
    evobot_default_volume: 15
    evobot_stay_time: 10

  vars_prompt:
    - name: discord_token
      private: false
      prompt: "Enter the DISCORD_APP_TOKEN"
      salt_size: 8
      unsafe: false

  tasks:

  - name: Copy docker image
    ansible.builtin.copy:
      src: "{{ copy_origin_path }}"
      dest: "{{ copy_destiny_path }}"

  - name: Load image
    community.docker.docker_image:
      load_path: "{{ copy_destiny_path }}"
      source: load
      name: "{{ image_name }}"
      tag: "{{ image_version }}"
  
  - name: Run container
    async: 360
    poll: 1
    community.docker.docker_container:
      name: "{{ container_name }}"
      image: "{{ container_name }}"
      state: started
      restart_policy: always
      env:
        TOKEN: "{{ discord_token }}"
        MAX_PLAYLIST_SIZE: "{{ evobot_max_playlist_size }}"
        LOCALE: "{{ evobot_locale }}"
        DEFAULT_VOLUME: "{{ evobot_default_volume }}"
        STAY_TIME: "{{ evobot_stay_time }}"
  
  - name: Clean docker old images
    async: 30
    poll: 1
    community.docker.docker_prune:
      images: true
