---
- name: Run Evobot in docker container
  hosts: all
  become: true
  gather_facts: false

  vars:
    repo_url: https://github.com/eritislami/evobot.git
    repo_branch: 2.8.1
    clone_path: /srv/evobot
    container_name: cleiton-rasta-bot
    evobot_max_playlist_size: 100
    evobot_locale: pt_br
    evobot_default_volume: 15
    evobot_stay_time: 10

  vars_prompt:
    - name: discord_token
      private: false
      prompt: "Enter the DISCORD_APP_TOKEN"
      salt_size: 8
      unsafe: false

  tasks:

  - name: Clone repository
    async: 60
    poll: 1
    ansible.builtin.git:
      repo: "{{ repo_url }}"
      dest: "{{ clone_path }}"
      version: "{{ repo_branch }}"

  - name: Build container image
    async: 1000
    poll: 1
    containers.docker.docker_image:
      name: "{{ container_name }}"
      path: "{{ clone_path }}"
  
  - name: Run container
    async: 360
    poll: 1
    containers.docker.docker_container:
      name: "{{ container_name }}"
      image: "{{ container_name }}"
      state: started
      env:
        TOKEN: "{{ discord_token }}"
        MAX_PLAYLIST_SIZE: "{{ evobot_max_playlist_size }}"
        LOCALE: "{{ evobot_locale }}"
        DEFAULT_VOLUME: "{{ evobot_default_volume }}"
        STAY_TIME: "{{ evobot_stay_time }}"
  
  - name: Clean docker old images
    async: 30
    poll: 1
    containers.docker.docker_prune:
      images: true
